Silent Auth
otpless-tech/otpless-flutter-plugin pull request #26
Opened 2024-05-30 08:23 UTC by digvijay-otpless

* android sdk update to 2.3.3 and ios sdk updated to 2.1.3
* web inspectable feature added for ios

2024-05-30 08:51 UTC, digvijay-otpless commented on example/android/app/src/main/AndroidManifest.xml
> +                    android:scheme= "otpless.5e62zcanetd9urnxpz80"/>
remove

2024-05-30 08:51 UTC, digvijay-otpless commented on example/ios/Runner/Info.plist
> +				<string>otpless.5e62zcanetd9urnxpz80</string>
remove

2024-05-30 08:57 UTC, sparsh-otpless requested changes
checkout the comments

2024-05-30 08:57 UTC, sparsh-otpless commented on example/lib/main.dart
> +      _otplessFlutterPlugin.initHeadless("5e62zcanetd9urnxpz80");
remove appid

2024-05-30 08:57 UTC, sparsh-otpless commented on example/lib/main.dart
> +    Map<String, dynamic> arg = {'appId': "5e62zcanetd9urnxpz80"};
remove appid

2024-05-30 08:57 UTC, sparsh-otpless commented on example/ios/Runner/Info.plist
> +				<string>otpless.5e62zcanetd9urnxpz80</string>
remove appid

2024-05-30 08:57 UTC, sparsh-otpless commented on example/lib/main.dart
> +      _otplessFlutterPlugin.initHeadless("5e62zcanetd9urnxpz80");
remove appid

2024-05-30 08:57 UTC, sparsh-otpless commented on example/lib/main.dart
> +      _otplessFlutterPlugin.initHeadless("5e62zcanetd9urnxpz80");
remove appid

2024-06-05 21:26 UTC, dev-otpless-tech approved these changes

2024-06-05 21:30 UTC, merged